### ISSUE TITLE
Account Creation Failed

### ISSUE THREAD

**Issue by digidan** [tarassh/fairy-wallet#28] opened 2018-09-15 17:01 UTC
I input my account name and hit pay with paypal and a pop up says account creation failed.

**Comment by digidan** [comment] 2018-09-15 17:02
![screen shot 2018-09-15 at 12 01 51 pm](https://user-images.githubusercontent.com/8356662/45588735-30c16a80-b8df-11e8-95b9-c3262d659d64.png)

Here is a screenshot.  I never get any actual request from paypal to login or anything.
On Mac OSX latest version of app

**Comment by fisher2003** [comment] 2018-09-16 01:10
I am getting the same problem.

**Comment by tarassh** [comment] 2018-09-16 11:57
Duplicate of #25. Please read recommendations from #25 .

**Closed by tarassh** 2018-09-16 11:57 UTC

**Comment by Sthrn** [comment] 2018-09-17 16:15
Me too, getting the same problem with payment......is it possible to pay with eos instead?
