### ISSUE TITLE
Can't create account with Fairy Wallet

### ISSUE THREAD

**Issue by dondaniel83** [tarassh/fairy-wallet#26] opened 2018-09-15 10:12 UTC
On the choose account name page when I click on: Create(Pay with Paypal) I got this error:

Account creation failed.

It shows like its processing the payment during a second but then the error show up.
The account name is good to go (available) aswell as the owner's public key and active.
I have tried a few more times but I-m always getting that same issue.

Thanks for any help.

**Comment by tarassh** [comment] 2018-09-15 16:51
Duplicate of #25 . Please read the #25

**Closed by tarassh** 2018-09-15 16:51 UTC

**Comment by zvaieakxfyr1** [comment] 2018-11-07 15:48
I have same as problem;
My account name "zvaieakxfyr1" was created successfully by:
https://eos-account-creator.com. 
But my account on fairy wallet was not activated yet! would you please be advise?
